# Generated by Django 5.0.6 on 2024-06-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("complaint_name", models.CharField(max_length=300)),
                ("complaint_type", models.CharField(max_length=300)),
                ("resolve", models.BooleanField()),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400)),
                ("total_income", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "pending_payment",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "happy_customer",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hotel Status",
            },
        ),
        migrations.CreateModel(
            name="IdCardType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=200, unique=True)),
                ("status", models.BooleanField()),
                ("check_in_status", models.BooleanField()),
                ("check_out_status", models.BooleanField()),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_type", models.CharField(max_length=200, unique=True)),
                ("price", models.IntegerField()),
                ("max_people", models.IntegerField()),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400)),
                ("address", models.CharField(max_length=300)),
                ("contact", models.CharField(max_length=300)),
                ("email", models.CharField(max_length=200)),
                ("id_card_no", models.CharField(max_length=20)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "id_card_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.idcardtype"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="web.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="web.position",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelReservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("receptionist", models.CharField(max_length=200)),
                ("check_in", models.DateField(blank=True, null=True)),
                ("check_out", models.DateField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "remaining_price",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "payment_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
                ("customer", models.ManyToManyField(to="web.customer")),
                (
                    "room",
                    models.ManyToManyField(related_name="reservation", to="web.room"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="web.roomtype",
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("salary", models.IntegerField(default=0)),
                ("joining_date", models.DateField()),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.department"
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.designation",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.shift"
                    ),
                ),
            ],
        ),
    ]
