# Generated by Django 5.0.6 on 2024-06-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="check_in",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="check_out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="hotelreservation",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="hotelreservation",
            name="room",
        ),
        migrations.AddField(
            model_name="hotelreservation",
            name="customer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotelreservation",
            name="room",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="web.room",
            ),
            preserve_default=False,
        ),
    ]
