# Generated by Django 5.0.6 on 2024-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_customer_check_in_customer_check_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="resolve",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
