# Generated by Django 5.0.6 on 2024-06-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_complaint_resolve"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_check_out",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
