# Generated by Django 5.0.6 on 2024-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_customer_is_check_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
