# Generated by Django 5.0.6 on 2024-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_employee_joining_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="delete_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
