# Generated by Django 5.0.6 on 2024-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_room_delete_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="delete_status",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
