# Generated by Django 5.0.6 on 2024-06-14 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0002_table_occupied"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="floor",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="restaurentapp.floor",
            ),
            preserve_default=False,
        ),
    ]
