# Generated by Django 5.0.6 on 2024-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurentapp', '0002_billreport_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdetail',
            name='total_revenue',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
