# Generated by Django 5.0.6 on 2024-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0003_table_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Meal"),
        ),
    ]
