# Generated by Django 5.0.6 on 2024-06-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0005_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
