# Generated by Django 5.0.4 on 2024-06-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0006_alter_customer_id_alter_order_id_alter_orderitem_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Table",
            new_name="TableData",
        ),
    ]
