# Generated by Django 5.0.4 on 2024-06-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0007_rename_table_tabledata"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_ready",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
