# Generated by Django 5.0.4 on 2024-06-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0008_orderitem_is_ready"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="is_ready",
        ),
    ]
