# Generated by Django 5.0.4 on 2024-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0009_remove_orderitem_is_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_ready",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
