# Generated by Django 5.0.6 on 2024-06-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0011_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealitem",
            name="image",
            field=models.ImageField(default=2, upload_to="Meal"),
            preserve_default=False,
        ),
    ]
