# Generated by Django 5.0.6 on 2024-06-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurentapp", "0013_organizationdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurentapp.orderitem",
                    ),
                ),
            ],
        ),
    ]
